SHELL_DANGEROUS_PATTERNS: dict[str, dict] = {
    "reverse_shell_bash": {
        "pattern": r"bash\s+-i\s*>&?\s*/dev/tcp/",
        "severity": "CRITICAL", "score": 98.0,
        "category": "backdoor",
        "description": "Reverse shell via bash TCP",
    },
    "reverse_shell_sh": {
        "pattern": r"sh\s+-i\s*>&?\s*/dev/tcp/",
        "severity": "CRITICAL", "score": 98.0,
        "category": "backdoor",
        "description": "Reverse shell via sh TCP",
    },
    "reverse_shell_python": {
        "pattern": r"python[23]?\s+-c\s+['\"].*socket.*connect.*dups?2?",
        "severity": "CRITICAL", "score": 98.0,
        "category": "backdoor",
        "description": "Reverse shell via Python",
    },
    "reverse_shell_perl": {
        "pattern": r"perl\s+-e\s+['\"].*socket.*connect.*STDIN",
        "severity": "CRITICAL", "score": 98.0,
        "category": "backdoor",
        "description": "Reverse shell via Perl",
    },
    "reverse_shell_nc": {
        "pattern": r"nc\s+(?:\-e\s+|.+?\-e\s+)",
        "severity": "CRITICAL", "score": 95.0,
        "category": "backdoor",
        "description": "Reverse shell via netcat",
    },
    "tcp_bind_shell": {
        "pattern": r"(?:/dev/tcp/|/dev/udp/)",
        "severity": "HIGH", "score": 85.0,
        "category": "backdoor",
        "description": "Acesso a socket TCP/UDP via shell",
    },
    "chained_shell": {
        "pattern": r"(?:&&|;|\|\|)\s*(?:bash|sh|zsh|python|perl)\s",
        "severity": "MEDIUM", "score": 55.0,
        "category": "command_injection",
        "description": "Shell encadeado após comando",
    },
    "shell_var_injection": {
        "pattern": r"(?:\$\(|\$\{|`)[^)]+?(?:bash|sh|curl|wget)[^)]*?(?:\)|}|`)",
        "severity": "HIGH", "score": 75.0,
        "category": "command_injection",
        "description": "Injeção de comando via variável shell",
    },
    "heredoc_script": {
        "pattern": r"<<\s*(?:EOF|SCRIPT|BASH|SH)\s*\n.*(?:curl|wget|bash|sh|python|eval|exec)",
        "severity": "HIGH", "score": 80.0,
        "category": "obfuscation",
        "description": "Heredoc com conteúdo malicioso",
    },
    "alias_hijack": {
        "pattern": r"alias\s+(?:curl|wget|bash|sh|sudo|git|npm|pip|python)=",
        "severity": "HIGH", "score": 80.0,
        "category": "persistence",
        "description": "Redirecionamento de alias para comando malicioso",
    },
    "function_hijack": {
        "pattern": r"(?:function\s+)?(?:curl|wget|bash|sh|sudo|git|npm|pip|python)\s*\(\)\s*\{",
        "severity": "HIGH", "score": 80.0,
        "category": "persistence",
        "description": "Redirecionamento de função shell para comando malicioso",
    },
    "history_wipe": {
        "pattern": r"(?:history\s+-c|>?\s*~/\..*history|unset\s+HISTFILE|export\s+HISTSIZE=0)",
        "severity": "MEDIUM", "score": 50.0,
        "category": "persistence",
        "description": "Limpeza de histórico - possível encobrimento",
    },
    "path_hijack": {
        "pattern": r"PATH\s*=\s*[^:]*\.(?:/bin|/sbin)[^:]*:",
        "severity": "HIGH", "score": 75.0,
        "category": "persistence",
        "description": "Modificação de PATH - possível hijacking de comando",
    },
    "user_cron": {
        "pattern": r"crontab\s+.*(?:curl|wget|bash|python|node|perl|ruby)",
        "severity": "CRITICAL", "score": 90.0,
        "category": "persistence",
        "description": "Cron job com execução remota",
    },
    "at_job": {
        "pattern": r"at\s+(?:now|midnight|noon)\s+(?:-f|-m)",
        "severity": "MEDIUM", "score": 55.0,
        "category": "persistence",
        "description": "Job agendado via at",
    },
    "encode_decode_chain": {
        "pattern": r"(?:echo|printf)\s+['\"].*['\"]\s*\|.*(?:base64|xxd|od|hexdump|openssl)",
        "severity": "HIGH", "score": 70.0,
        "category": "obfuscation",
        "description": "Chain de encode/decode - possível payload ofuscado",
    },
    "multiple_pipes": {
        "pattern": r"\|.*\|.*\|.*\|",
        "severity": "LOW", "score": 25.0,
        "category": "obfuscation",
        "description": "Múltiplos pipes - possível chain de ofuscação",
    },
    "dev_null_redirect": {
        "pattern": r"(?:2>&1|>/dev/null\s*&|&>/dev/null)",
        "severity": "LOW", "score": 15.0,
        "category": "obfuscation",
        "description": "Redirecionamento de saída - possível ocultação",
    },
}
