from __future__ import annotations

from pathlib import Path

from security_scanner.models import ScanResult, SEVERITY_SORT_PRIORITY
from security_scanner.reporting.report import ReportGenerator


class MarkdownReport(ReportGenerator):
    extension = "md"

    def generate(self, result: ScanResult) -> str:
        lines: list[str] = []
        lines.append(f"# Security Scan Report — `{result.target}`")
        lines.append("")
        lines.append(f"- **Scan ID**: `{result.scan_id}`")
        lines.append(f"- **Timestamp**: {result.timestamp}")
        lines.append(f"- **Duration**: {result.duration_ms}ms")
        lines.append(f"- **Total files**: {result.total_files}")
        lines.append(f"- **Total findings**: {result.total_findings}")
        lines.append(f"- **Risk score**: {result.risk_score:.1f}")
        lines.append("")

        sc = result.severity_counts
        if sc:
            lines.append("## Severity Breakdown")
            lines.append("")
            for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"):
                count = getattr(sc, sev.lower(), 0)
                if count:
                    lines.append(f"- **{sev}**: {count}")
            lines.append("")

        if result.correlations:
            lines.append("## Correlations")
            lines.append("")
            for i, ev in enumerate(result.correlations, 1):
                lines.append(f"### {i}. {ev.get('name', '')}")
                lines.append(f"- **Rule**: {ev.get('rule_id', '')}")
                lines.append(f"- **Severity**: {ev.get('severity', '')}")
                lines.append(f"- **Score**: {ev.get('score', 0)}")
                lines.append(f"- **Description**: {ev.get('description', '')}")
                if ev.get("mitre_technique"):
                    lines.append(f"- **MITRE**: {ev['mitre_technique']}")
                if ev.get("recommendation"):
                    lines.append(f"- **Recommendation**: {ev['recommendation']}")
                lines.append("")

        if result.findings:
            lines.append("## Findings")
            lines.append("")
            sorted_f = sorted(result.findings, key=lambda f: SEVERITY_SORT_PRIORITY.get(f.severity, 9))
            for i, f in enumerate(sorted_f, 1):
                emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "⚪", "INFO": "🔵"}
                sev_emoji = emoji.get(f.severity, "⚪")
                lines.append(f"### {sev_emoji} #{i} — {f.description}")
                lines.append(f"- **Severity**: {f.severity}")
                lines.append(f"- **Score**: {f.score:.1f}")
                lines.append(f"- **File**: `{f.file_path}`")
                if f.line:
                    lines.append(f"- **Line**: {f.line}")
                if f.category:
                    lines.append(f"- **Category**: {f.category}")
                if f.detected_terms:
                    lines.append(f"- **Terms**: `{'`, `'.join(f.detected_terms)}`")
                if f.evidence:
                    lines.append(f"- **Evidence**:```\n{f.evidence[:300]}\n```")
                if f.recommendation:
                    lines.append(f"- **Fix**: {f.recommendation}")
                lines.append("")

        lines.append("---")
        lines.append("*Report generated by VSCode Security Scanner*")
        return "\n".join(lines)
